version: '3.8'

services:
  omr-scanner:
    build: .
    ports:
      - "5000:5000"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - DEBUG=True
      - FLASK_ENV=development
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
    restart: unless-stopped
