[providers]
python = "3.11"

[phases.setup]
nixPkgs = ["python311", "pip", "bash"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "echo 'Build phase completed'",
    "chmod +x start.sh"
]

[start]
cmd = "./start.sh"
